#!/bin/sh

# --------------------------
# CURSOR
# --------------------------
xsetroot -cursor_name left_ptr

# --------------------------
# MONITORS & DESKTOPS
# --------------------------
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# --------------------------
# GAPS & BORDERS
# --------------------------
bspc config border_width 3
bspc config window_gap 5
bspc config top_padding 35
bspc config split_ratio 0.5
bspc config focus_follows_pointer true

# --------------------------
# COLORS
# --------------------------
bspc config normal_border_color "#24283b"
bspc config active_border_color "#7aa2f7"
bspc config focused_border_color "#7aa2f7"
bspc config presel_feedback_color "#bb9af7"

# --------------------------
# AUTOSTART
# --------------------------
dbus-update-activation-environment --systemd DISPLAY XDG_CURRENT_DESKTOP=bspwm &
/usr/libexec/xdg-desktop-portal-gtk &
blueman-applet &
nm-applet &
dunst &

# Launch Polybar
killall -q polybar
polybar &

# Optional compositor
# picom &
