set -g status-position bottom
set -g status-justify left
set -g status-style "bg=#1a1b26,fg=#a9b1d6" 
#active:
setw -g window-status-current-format "#[fg=#7aa2f7,bg=#1a1b26]#[fg=#15161e,bg=#7aa2f7]#I #[fg=#c0caf5,bg=#3b4261] #{?#{==:#{pane_current_path},#HOME},~,#{b:pane_current_path}} #[fg=#3b4261,bg=#1a1b26]"
#inactive:
setw -g window-status-format "#[fg=#414868,bg=#1a1b26]#[fg=#c0caf5,bg=#414868]#I #[fg=#a9b1d6,bg=#24283b] #{?#{==:#{pane_current_path},#HOME},~,#{b:pane_current_path}} #[fg=#24283b,bg=#1a1b26]"

set -g status-right-length 100
set -g status-right "#[fg=#f7768e,bg=#1a1b26]#[fg=#15161e,bg=#f7768e] #[fg=#c0caf5,bg=#3b4261] #(whoami) #[fg=#3b4261,bg=#1a1b26] #[fg=#7dcfff,bg=#1a1b26]#[fg=#15161e,bg=#7dcfff]󱎫 #[fg=#c0caf5,bg=#3b4261] %H:%M #[fg=#3b4261,bg=#1a1b26]"

set -g status-left ""
